import type { Metadata } from "next";
import { Raleway } from "next/font/google";
// @ts-ignore
import "@/assets/styles/globals.css";
import Header from "@/components/Header";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Sample Internet Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
