import type { Product, User, Order } from "@prisma/client";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Mobile Legends: Bang Bang",
    description: "Пополнение алмазов в Mobile Legends. Быстрое зачисление в течение 5-10 минут.",
    category: "GAME" as any,
    gameType: "MOBILE_LEGENDS" as any,
    image: "https://placehold.co/200x200/1a2444/fefcfb?text=ML",
    basePrice: 100,
    currentPrice: 90,
    discount: 10,
    currency: "₽",
    isActive: true,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "PUBG Mobile UC",
    description: "Пополнение UC в PUBG Mobile. Официальное пополнение через наш сайт.",
    category: "GAME" as any,
    gameType: "PUBG_MOBILE" as any,
    image: "https://placehold.co/200x200/1a2444/fefcfb?text=PUBG",
    basePrice: 150,
    currentPrice: 125,
    discount: 17,
    currency: "₽",
    isActive: true,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Free Fire Алмазы",
    description: "Пополнение алмазов в Free Fire. Быстрое зачисление.",
    category: "GAME" as any,
    gameType: "FREE_FIRE" as any,
    image: "https://placehold.co/200x200/1a2444/fefcfb?text=FF",
    basePrice: 80,
    currentPrice: 80,
    discount: 0,
    currency: "₽",
    isActive: true,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Steam пополнение (СНГ)",
    description: "Пополнение Steam кошелька для аккаунтов из СНГ.",
    category: "SERVICE" as any,
    gameType: "STEAM" as any,
    image: "https://placehold.co/200x200/1a2444/fefcfb?text=Steam",
    basePrice: 200,
    currentPrice: 200,
    discount: 0,
    currency: "₽",
    isActive: true,
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockUser: User = {
  id: "user-1",
  telegramId: "123456789",
  username: "testuser",
  firstName: "Тест",
  lastName: "Пользователь",
  createdAt: new Date(),
  updatedAt: new Date(),
};
